# Sequence 4 : Introduction Numpy

## Pourquoi Numpy?

Numpy est une librairie d'extention à Python pour les tableaux multidimentionnels.
- calcul vectoriel avec représentation multidimentionnelle (ex : vecteur 1D, serie temporelle 2D, IRMAnat 3D, IRM Fonctionnelle 4D)
- efficace en gestion mémoire (proche hardware - gd enssemble de nbres ordonnés)
- conçu pour le calcul scientifique
- "brique" de base pour tout l'ecosystème scientifique (pandas/nipype/mne/scipy/...)

In [2]:
import numpy as np             # convention d'import
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

Opérations numériques rapides :

In [3]:
L = list(range(1000))             # Liste
%timeit [i**2 for i in L]

a = np.arange(1000)         # Numpy array
%timeit a**2

#pouquoi ? numpy est écrit en C !

1000 loops, best of 3: 281 µs per loop
The slowest run took 12.98 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.17 µs per loop


Doc : http://docs.scipy.org/

Aide interractive :

In [6]:
np.array?

In [7]:
np.con*?

## Création 1 : Multi-dimention

### 1-D

In [4]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [5]:
a.ndim

1

In [6]:
a.shape

(4,)

In [7]:
a.size
# nbre d'elements total

4

### 2-D, 3-D, ... N-D

In [8]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print('b : ', b)
print('b.ndim : ', b.ndim)
print('b.shape : ', b.shape)
print('b.size : ', b.size)

# attention à la necessité de dimentions cohérentes 
# b = np.array([[0, 1, 2], [3, 4, 5, 6]]) va pas marcher

b :  [[0 1 2]
 [3 4 5]]
b.ndim :  2
b.shape :  (2, 3)
b.size :  6


In [9]:
c = np.array([
        [[1,2,3], [2,3,4], [3,4,5], [4,5,6]],
        [[2,3,4], [3,4,5], [4,5,6], [5,6,7]],
        [[3,4,5], [4,5,6], [5,6,7], [6,7,8]],
        [[4,5,6], [5,6,7], [6,7,8], [7,8,9]],
        [[5,6,7], [6,7,8], [7,8,9], [8,9,10]]
    ])
print('c.ndim : ', c.ndim)
print('c.shape : ', c.shape)
print('c.size : ', c.size)

c.ndim :  3
c.shape :  (5, 4, 3)
c.size :  60


<img src="./img/sequence4_array_dims.png">

## Création 2 : Fonctions

En pratique, on entre rarement les nombres à la main...

### Eléments réguliairement espacés :

In [16]:
a = np.arange(10) # 0 .. n-1  (!)
a

#equivalent du range mais en numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.arange(1, 9, 2) # début, fin (exclusive), pas
b

array([1, 3, 5, 7])

### Ou espacés en donnant le nombre de points :

In [18]:
c = np.linspace(0, 1, 6)   # début, fin, nombre de points
c

# attention, ici c'est inclus !

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [19]:
d = np.linspace(0, 1, 5, endpoint=False)
d

#(intro mot clef)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

### Tableaux usuels :

In [18]:
a = np.ones((3, 3))  # np.ones((3, 3, 3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
b = np.zeros((2, 2))
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [23]:
c = np.random.rand(10)      # distribution uniforme entre [0, 1]
c

array([ 0.37152159,  0.09916289,  0.0275049 ,  0.35338348,  0.88942108,
        0.83451904,  0.9364776 ,  0.54263968,  0.14620334,  0.42149458])

In [20]:
d = np.random.randn(4)      # distribution gaussian de moy 0 et stdv 1
d

array([-1.96710428,  1.0339116 ,  0.631155  , -0.80162558])

In [22]:
e = np.random.randint(0, 5, size=(2, 4))
e

array([[2, 3, 4, 1],
       [2, 3, 4, 4]])

## Création 3 : dtype

In [24]:
a = np.array([0, 1, 2, 3])
print(a)
a.dtype

[0 1 2 3]


dtype('int64')

In [25]:
b = np.array([0., 1., 2., 3.])
print(b)
b.dtype

[ 0.  1.  2.  3.]


dtype('float64')

In [26]:
import numpy as np
d = np.array([1.33,2,3.,4])
print(d)
d.dtype

# en numpy, les tableaux sont forcément homogène car ils sont continus et compacts en mémoire.
# lors de mix numpy prends le dtype le plus utile 

[ 1.33  2.    3.    4.  ]


dtype('float64')

### Vous devez expliciter le dtype à la création

In [27]:
c1 = np.arange(10, dtype='float64')
print(c1)
c1.dtype

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


dtype('float64')

In [27]:
c2 = np.arange(10, dtype='int64')
print(c2)
c2.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')


### Le type par défaut est généralement "float64" 

In [28]:
a = np.ones((3, 3), dtype = "int32")
print(a)
a.dtype

# d'ou, la bonne pratique est de spécifier le dtype à chaque fois
# cf sous matlab c'est l'enfer.

[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int32')

### Autres types :

In [29]:
# Complexe :
a = np.array([1+2j, 3+4j, 5+6*1j])
a.dtype

dtype('complex128')

In [30]:
# Booléen
b = np.array([True, False, False, True])
b.dtype

dtype('bool')

In [32]:
# String
c = np.array(['Bonjour', 'Hello', 'Hallo',])
c.dtype             # <--- strings contenant max. 7 lettres

# U7 : unique 7 caractere

dtype('<U7')

## Introduction aux opérations

In [38]:
c = np.arange(10, dtype='float64')
d = np.arange(10, dtype='float64')

print('c : ', c)
print('d : ', d)

c :  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
d :  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [39]:
c+1

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [40]:
c+d

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [41]:
c*10+d

array([  0.,  11.,  22.,  33.,  44.,  55.,  66.,  77.,  88.,  99.])

In [47]:
res = np.log10(c)

/home/sgarcia/.virtualenvs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log10
  if __name__ == '__main__':


In [51]:
flags = np.isinf(res)
flags

array([ True, False, False, False, False, False, False, False, False, False], dtype=bool)

In [43]:
np.inf

inf

In [44]:
-np.inf

-inf

In [45]:
np.nan

nan

In [56]:
a = np.arange(9)
print(a)
flags = (a>5)
flags

[0 1 2 3 4 5 6 7 8]


array([False, False, False, False, False, False,  True,  True,  True], dtype=bool)

In [58]:
a = np.arange(9)
print(a)
flags = (a>2) & (a<=6)
flags



[0 1 2 3 4 5 6 7 8]


array([False, False, False,  True,  True,  True,  True, False, False], dtype=bool)

In [59]:
a = np.arange(9)
print(a)
flags = (a>2) | (a<=6)
flags


[0 1 2 3 4 5 6 7 8]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [60]:
flags2 = ~flags
flags2

array([False, False, False, False, False, False, False, False, False], dtype=bool)